# TODO: - CUDA compilation (where to get cudatoolkit from? nvidia or conda-forge)?
#       - linking problem when using cudatoolkit from nvidia channel               
#       - currently, using cudatoolkit from nvidia channel and not using the generic compiler('c') / compiler('cxx')

# TODO  - copy cuda kernel file to PREFIX

package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - git
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]
    #- cudatoolkit

about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
