package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake >=3.23
    - make  # [not win]
    - git
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]
    - cuda-toolkit

about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
