package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  skip: true #  [win]

outputs:
  - name: parallelproj
    script: build_openmp.sh  # [not win]
    requirements:
      host:
      build:
        - cmake >=3.23
        - ninja
        - git
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
      run:
        - libgomp  # [linux]
        - llvm-openmp  # [osx]

  - name: parallelproj-cuda
    script: build_cuda.sh  # [not win]
    requirements:
      host:
      build:
        - cmake >=3.23
        - ninja
        - git
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - cuda-toolkit
      run:
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - cuda-toolkit

about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT
  summary: 'parallelized TOF PET projectors'
