package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  missing_dso_whitelist:
    - lib/libgomp.so.1            # [linux]
    - $RPATH/librt.so.1           # [linux]
    - $RPATH/libpthread.so.0      # [linux]
    - $RPATH/libdl.so.2           # [linux]
    - lib/libstdc++.so.6          # [linux]
    - $RPATH/libc.so.6            # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]
    - lib/libgomp.so.1            # [linux]
    - $RPATH/libc.so.6            # [linux]


requirements:
  build:
    - cmake >=3.23
    - make  # [not win]
    - ninja  # [win]
    - git
    - doxygen
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]
    - cuda-toolkit

about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
