package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  number: {{ GIT_DESCRIBE_NUMBER }}
  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

  run:
    - python >=3.7
    - numpy >=1.18
    - scipy >=1.2
    - matplotlib >=3.2.1
    - numba >=0.49
  
about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
