package:
  name: parallelproj
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake
    - git

about:
  home: https://github.com/gschramm/parallelproj
  license:  MIT License
  summary: 'parallelized TOF PET projectors'
