version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment.yml
# This part is necessary otherwise the project is not built
python:
  install:
    - method: pip
      path: .
#version: 2
#
#build:
#  os: "ubuntu-20.04"
#  tools:
#    python: "3.8"
#
#sphinx:
#  fail_on_warning: true
#
#conda:
#  environment: environment.yml
#
#python:
#  # Install our python package before building the docs
#  install:
#    - method: pip
#      path: .
#
#formats:
#  - pdf
#  - epub
#
