name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx>=7.0
  - sphinx_rtd_theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - jupytext
  - ipykernel
  - libparallelproj
