name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - libparallelproj
  - numpy>=1.20
  - matplotlib
  - sphinx<7
  - sphinx_rtd_theme
  - array-api-compat
