name: conda_and_docs_build

on:
  release:
    types: [published]
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  conda_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: conda-build
      uses: paskino/conda-package-publish-action@v1.4.4
      with:
        subDir: 'recipe'
        channels: '-c conda-forge -c nvidia'
        convert_win: true
        convert_osx: false
