on: push

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge, nvidia
          auto-update-conda: true
      - name: install conda build
        run: |
          conda install conda-build
      - name: conda build
        run: |
          conda build -c conda-forge -c nvidia .
