name: conda_and_docs_build

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  conda_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: conda-build
      uses: paskino/conda-package-publish-action@v1.4.4
      with:
        subDir: 'recipe'
        channels: '-c conda-forge -c nvidia'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        convert_win: false
        convert_osx: false
